Repository arindal1/yolov5-onnx-object-recognition, pull requests merged in 2023-10, with the labels that each got.

#4 Created directory: `programs/JavaScript/`
  misc/programs/JavaScript/0001 The Fiscal Code (L-H)/README.md
  misc/programs/JavaScript/0001 The Fiscal Code (L-H)/TheFiscalCode.js
  misc/programs/JavaScript/README.md
Labels: enhancement, hacktoberfest-accepted

#12 Added todolist using React.js
  misc/webdev/todolist/.gitignore
  misc/webdev/todolist/README.md
  misc/webdev/todolist/package-lock.json
  misc/webdev/todolist/package.json
  misc/webdev/todolist/public/favicon.ico
  misc/webdev/todolist/public/index.html
  misc/webdev/todolist/src/App.css
  misc/webdev/todolist/src/App.js
  misc/webdev/todolist/src/components/TodoInput.js
  misc/webdev/todolist/src/components/TodoList.js
  misc/webdev/todolist/src/index.js
Labels: enhancement, hacktoberfest-accepted

#13 Updated: `ConvertPyTorchModels.ipynb`
  ConvertPyTorchModels.ipynb
Labels: bug

#14 Added pre commit hook
  .pre-commit-config.yaml
Labels: hacktoberfest-accepted

#17 Added: `Prolog` space
  misc/programs/Prolog/0001 Max and Min/README.md
  misc/programs/Prolog/0001 Max and Min/maxmin.pl
  misc/programs/Prolog/0002 Resistance and Resistive Circuits [L-B]/README.md
  misc/programs/Prolog/0002 Resistance and Resistive Circuits [L-B]/resistanceresistive.pl
  misc/programs/Prolog/0003 Horizontal and Vertical Line Segments [L-B]/README.md
  misc/programs/Prolog/0003 Horizontal and Vertical Line Segments [L-B]/horizontalvertical.pl
  misc/programs/Prolog/0004 Towers of Hanoi [L-A]/README.md
  misc/programs/Prolog/0004 Towers of Hanoi [L-A]/towerofhanoi.pl
  misc/programs/Prolog/README.md
Labels: enhancement, hacktoberfest-accepted

#18 Flappy-Bird: A Legendary Game
  misc/webdev/Flappy-Bird/Readme.md
  misc/webdev/Flappy-Bird/bottompipe.png
  misc/webdev/Flappy-Bird/demo.png
  misc/webdev/Flappy-Bird/flappybird.png
  misc/webdev/Flappy-Bird/flappybirdbg.png
  misc/webdev/Flappy-Bird/index.html
  misc/webdev/Flappy-Bird/script.js
  misc/webdev/Flappy-Bird/style.css
  misc/webdev/Flappy-Bird/toppipe.png
Labels: enhancement, hacktoberfest-accepted

#19 Space-Invader: A JavaScript Masterpiece
  misc/webdev/Space-Invader/Readme.md
  misc/webdev/Space-Invader/audio/Background-Music.mp4
  misc/webdev/Space-Invader/audio/bomb.mp3
  misc/webdev/Space-Invader/audio/bonus.mp3
  misc/webdev/Space-Invader/audio/enemyShoot.wav
  misc/webdev/Space-Invader/audio/explode.wav
  misc/webdev/Space-Invader/audio/gameOver.mp3
  misc/webdev/Space-Invader/audio/select.mp3
  misc/webdev/Space-Invader/audio/shoot.wav
  misc/webdev/Space-Invader/audio/start.mp3
  misc/webdev/Space-Invader/img/button.png
  misc/webdev/Space-Invader/img/demo.png
  misc/webdev/Space-Invader/img/invader.png
  misc/webdev/Space-Invader/img/spaceship.png
  misc/webdev/Space-Invader/img/startScreenBackground.png
  misc/webdev/Space-Invader/index.html
  misc/webdev/Space-Invader/script.js
Labels: documentation, enhancement, hacktoberfest-accepted

#24 added Word_Search in misc/webdev
  misc/webdev/Word_Search/.DS_Store
  misc/webdev/Word_Search/index.html
  misc/webdev/Word_Search/public/yellow_esport_background_03.jpg
  misc/webdev/Word_Search/script.js
  misc/webdev/Word_Search/style.css
Labels: hacktoberfest-accepted

#25 Added NumberGuess in misc/webdev
  .DS_Store
  misc/.DS_Store
  misc/webdev/NumberGuess/index.html
  misc/webdev/NumberGuess/index.js
  misc/webdev/NumberGuess/style.css
Labels: hacktoberfest-accepted
